- platform: template
  sensors:
      upstairs_motion:
          value_template: '{{ is_state("sensor.upstairs_burglar", "8") }}'
          friendly_name: 'Upstairs Motion'
      upstairs_tamper:
          value_template: '{{ is_state("sensor.upstairs_burglar", "3") }}'
          friendly_name: 'Upstairs Tampering'


