  - alias: "Up Stairs Presence On"
    id: up_stairs_prsence_on
    trigger:
        platform: state
        entity_id: binary_sensor.upstairs_motion # find-motion-upstairs
        to: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.presence_upstairs

  - alias: "Up Stairs Presence Off Immediate"
    id: up_stairs_prsence_off_immediate
    condition:
        condition: state
        entity_id: input_select.delay_upstairs
        state: "Immediate"
    trigger:
        platform: state
        entity_id: binary_sensor.upstairs_motion # find-motion-upstairs
        to: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.presence_upstairs

  - alias: "Up Stairs Presence Off 2 Minutes"
    id: up_stairs_prsence_off_2_minutes
    condition:
        condition: state
        entity_id: input_select.delay_upstairs
        state: "2 Minutes"
    trigger:
        platform: state
        entity_id: binary_sensor.upstairs_motion # find-motion-upstairs
        to: 'off'
        for:
            minutes: 2
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.presence_upstairs

  - alias: "Up Stairs Presence Off 5 Minutes"
    id: up_stairs_prsence_off_5_minutes
    condition:
        condition: state
        entity_id: input_select.delay_upstairs
        state: "5 Minutes"
    trigger:
        platform: state
        entity_id: binary_sensor.upstairs_motion # find-motion-upstairs
        to: 'off'
        for:
            minutes: 5
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.presence_upstairs

  - alias: "Mark is Home"
    id: mark_is_home
    trigger:
        - platform: state
          entity_id: input_boolean.presence_home_mark
          state: 'on'
    action:
        - service: input_select.select_option
          data:
              entity_id: input_select.presence_room_mark
              option: "At Home"

  - alias: "Mark is Away"
    id: mark_is_away
    trigger:
        - platform: state
          entity_id: input_boolean.presence_home_mark
          state: 'off'
    action:
        - service: input_select.select_option
          data:
              entity_id: input_select.presence_room_mark
              option: "Away"

  - alias: "Router has Detected Mark"
    id: router_has_detected_mark
    condition:
        - condition: state
          entity_id: input_boolean.presence_home_mark
          state: 'off'
    trigger:
        - platform: state
          entity_id: device_tracker.phone_mark
          state: 'home'
    action:
        - service: homeassistant.turn_on
          entity_id: input_boolean.presence_home_mark

  - alias: "Mark has disconnected"
    id: mark_has_disconnected
    condition:
        - condition: state
          entity_id: input_boolean.presence_home_mark
          state: 'on'
    trigger:
        - platform: state
          entity_id: device_tracker.phone_mark
          state: 'not_home'
          for:
              minutes: 3
    action:
        - service: homeassistant.turn_off
          entity_id: input_boolean.presence_home_mark