homeassistant:
    name: Home
    customize: !include customize.yaml
    latitude: !secret latitude
    longitude: !secret longitude
    # Impacts weather/sunrise data (altitude above sea level in meters)
    elevation: 186
    # metric for Metric, imperial for Imperial
    unit_system: imperial
    # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    time_zone: America/Chicago

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
    api_password: !secret api_password
#    base_url: !secret host

# Checks for available updates
updater:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

recorder:
    db_url: !secret db_url
    purge_interval: 2
    purge_keep_days: 7

# Text to speech
tts:
    platform: google

group: !include groups.yaml

nest:
    client_id: !secret nest_id
    client_secret: !secret nest_secret

zwave:
    usb_path: /dev/ttyACM0
    config_path: /srv/homeassistant/src/python-openzwave/openzwave/config
    polling_interval: 60000
    # debug: 1
    # autoheal: False
    device_config: !include zwave_device_config.yaml


#mqtt:
#    broker: 192.168.1.4
#    port: 1883
#    keepalive: 60
#    client_id: homeassistant
#    username: !secret mqtt_username
#    password: !secret mqtt_password
#    protocol: 3.1

cover:
    - platform: myq
      username: !secret myq_username
      password: !secret myq_password
      type: chamberlain

camera:
    - platform: foscam
      username: !secret foscam_username
      password: !secret foscam_password
      ip: 192.168.1.25
      name: Living Room Camera
    - platform: foscam
      username: !secret foscam_username
      password: !secret foscam_password
      ip: 192.168.1.20
      name: Front Porch Camera
    
    

notify:
    - name: pushbullet
      platform: pushbullet
      api_key: !secret pushbullet_key

emulated_hue:
    type: alexa
    expose_by_default: true
    exposed_domains:
        - light
        - switch

remote:
    - platform: harmony
      name: Living Room
      host: 192.168.1.6

device_tracker:
    - platform: netgear
      password: !secret netgear_password

input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensor
binary_sensor: !include_dir_merge_list binary_sensor
script: !include_dir_merge_named script

timer:
    living_room:
        name: Living Room
        icon: mdi:timer
    dining_room:
        name: Dining Room
        icon: mdi:timer
    kitchen:
        name: Kitchen
        icon: mdi:timer
    upstairs:
        name: Up Stairs
        icon: mdi:timer
