- platform: template
  sensors:
      battery_motion_living_room:
          value_template: '{{ states.zwave.living_room.attributes.battery_level }}'
          friendly_name: 'Living Room Sensor Battery Level'
          unit_of_measurement: '%'

- platform: template
  sensors:
      battery_motion_dining_room:
          value_template: '{{ states.zwave.dining_room.attributes.battery_level }}'
          friendly_name: 'Dining Room Sensor Battery Level'
          unit_of_measurement: '%'

- platform: template
  sensors:
      battery_motion_kitchen:
          value_template: '{{ states.zwave.kitchen.attributes.battery_level }}'
          friendly_name: 'Kitchen Sensor Battery Level'
          unit_of_measurement: '%'

- platform: template
  sensors:
      battery_motion_upstairs:
          value_template: '{{ states.zwave.upstairs.attributes.battery_level }}'
          friendly_name: 'Up Stairs Sensor Battery Level'
          unit_of_measurement: '%'

- platform: template
  sensors:
      battery_lock_back:
          value_template: '{{ states.zwave.back_door.attributes.battery_level }}'
          friendly_name: 'Back Door Lock Battery Level'
          unit_of_measurement: '%'

- platform: template
  sensors:
      battery_lock_garage:
          value_template: '{{ states.zwave.garage_door.attributes.battery_level }}'
          friendly_name: 'Garage Door Lock Battery Level'
          unit_of_measurement: '%'


- platform: template
  sensors:
      battery_dining_room_smoke_alarm:
          value_template: '{{ states.zwave.dining_room_smoke.attributes.battery_level }}'
          friendly_name: 'Dining Room Smoke Alarm Battery'
          unit_of_measurement: '%'