- alias: "Dining Room Smoke Alarm Notification"
  initial_state: 'on'
  trigger:
      platform: state
      entity_id: sensor.dining_room_smoke_alarm
  action:
      - service: notify.pushbullet_mark
        data:
            message: "The Dining Room Smoke Alarm status changed to {{ states.sensor.dining_room_smoke_alarm.state }}"
            title: "Dining Room Smoke Alarm"
      - service: notify.pushbullet_lauren
        data:
            message: "The Dining Room Smoke Alarm status changed to {{ states.sensor.dining_room_smoke_alarm.state }}"
            title: "Dining Room Smoke Alarm"
      - service: persistent_notification.create
        data:
            title: "Dining Room Smoke Alarm"
            notification_id: "dining_room_smoke_alarm"
            message: "The Dining Room Smoke Alarm status changed to {{ states.sensor.dining_room_smoke_alarm.state }}"
