- alias: "Update Available Notification"
  initial_state: 'on'
  trigger:
      platform: state
      entity_id: updater.updater
  action:
      - service: notify.pushbullet
        data:
            message: "HomeAssistant {{ states('updater.updater') }} is now available"
            title: "Update HASS"
      - service: persistent_notification.create
        data:
            title: "Update Available"
            notification_id: "update_available"
            message: >
                Home Assistant {{ states('updater.updater') }} is available, please [update](https://home-assistant.io/getting-started/installation-raspberry-pi-all-in-one/#upgrading).
